version: 2.1

jobs:
  build:
    parameters:
      npm-package:
        type: string
    docker:
      - image: circleci/node:14
    steps:
      - run: |
          npm install << parameters.npm-package >>
      - run: |
          npm ls phantomjs-prebuilt

workflows:
  main:
    jobs:
      - build:
          matrix:
            parameters:
              npm-package:
                - phantomjs-prebuilt@2.1.16
                - phantomjs-prebuilt@1.9.20
